name: Push Notification Workflow

on:
  schedule:
    # Schedule: Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache dependencies to avoid reinstalling every time
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies (only if needed)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Only run the script now
      - name: Run script
        env:
          ACCESS_TOKEN: ${{ secrets.PUSHBULLET_ACCESS_TOKEN }}
        run: python slots.py
