name: Push Notification Workflow

on:
  schedule:
    # Schedule: Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install PushbulletPythonLibrary

      - name: Run script
        env:
          ACCESS_TOKEN: ${{ secrets.PUSHBULLET_ACCESS_TOKEN }}
        run: python slots.py

